esphome:
  name: esp-32-ble-receiver
  friendly_name: ESP 32 BLE Receiver

ota:
  - platform: esphome

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE
  logs:
    esp32_ble_tracker: ERROR

external_components:
  - source:
      type: git
      url: https://github.com/spbrogan/esphome
      ref: PolledSensor
    components: [ hughes_power_watchdog ]
    refresh: 1s

api: 
  encryption:
    key: !secret ble_relay_enc

wifi:
  networks:
  - ssid: !secret wifi2_ssid
    password: !secret wifi2_password
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  ap:
  
captive_portal:

esp32_ble_tracker:
  scan_parameters:
    interval: 320ms
    window: 120ms
    duration: 60s
    active: true

mopeka_ble:
  show_sensors_without_sync: true
  
bluetooth_proxy:
  active: true

ble_client:
  - mac_address: **WATCHDOG MAC** USE BLE SNIFFER TO LOCATE
    id: power_watchdog
    
switch:
  - platform: ble_client
    ble_client_id: power_watchdog
    name: "Watchdog Monitoring"
  - platform: restart
    name: esp-32-ble-receiver Restart

binary_sensor:
  - platform: status
    name: "Node Status"
    id: system_status

sensor:
  - platform: hughes_power_watchdog
    ble_client_id: power_watchdog
    voltage_line_1:
      name: "Watchdog Voltage Line 1"
      accuracy_decimals: 0
    current_line_1:
      name: "Watchdog Current Line 1"
      accuracy_decimals: 1
    power_line_1:
      name: "Watchdog Power Line 1"
      accuracy_decimals: 0
    voltage_line_2:
      name: "Watchdog Voltage Line 2"
      accuracy_decimals: 0
    current_line_2:
      name: "Watchdog Current Line 2"
      accuracy_decimals: 1
    power_line_2:
      name: "Watchdog Power Line 2"
      accuracy_decimals: 0
    combined_power:
      name: "Watchdog Power"
      accuracy_decimals: 0
    total_power:
      name: "Watchdog Cumulative Power Usage"
      accuracy_decimals: 1
    error_code_value:
      name: "Watchdog Error Code"
    error_code_text:
      name: "Watchdog Error Text"
  - platform: mopeka_std_check
    mac_address: **MOPEKA MAC MOPEKA_BLE WILL LOG ALL MAC'S IT DETECTS**
    tank_type: NORTH_AMERICA_30LB_VERTICAL
    propane_butane_mix: 100%
    distance:
        id: right_tank_distance
        name: "Right Propane Distance"
    level:
        id: right_tank_level
        name: "Right Tank Level"
    battery_level:
        name: "Right Propane Battery Level"
  - platform: mopeka_std_check
    mac_address: **MOPEKA MAC MOPEKA_BLE WILL LOG ALL MAC'S IT DETECTS**
    tank_type: NORTH_AMERICA_30LB_VERTICAL
    propane_butane_mix: 100%
    distance:
      id: left_tank_distance
      name: "Left Propane Distance"
    level: 
      id: left_tank_level
      name: "Left Tank Level"
    battery_level:
        name: "Left Propane Battery Level"
  - platform: mopeka_std_check
    mac_address: **MOPEKA MAC MOPEKA_BLE WILL LOG ALL MAC'S IT DETECTS**
    tank_type: NORTH_AMERICA_20LB_VERTICAL
    propane_butane_mix: 100%
    distance:
        id: extra_tank_distance
        name: "Extra Propane Distance"
    level:
      id: extra_tank_level
      name: "Extra Tank Level"
    battery_level:
        name: "Extra Propane Battery Level"

text_sensor:
  - platform: version
    name: Watchdog ESPHome Version
    id: watchdog_esphome_version
  - platform: wifi_info
    ip_address:
      name: Watchdog Host IP Address
      id: watchdog_host_ip
      icon: mdi:fingerprint
    ssid:
      name: Watchdog Host SSID
      id: watchdog_host_ssid
      icon: "mdi:router-wireless"
  - platform: template
    id: watchdog_host_mac_address
    name: Watchdog Monitor MAC Address
    lambda: 'return {WiFi.macAddress().c_str()};'
    icon: mdi:fingerprint
    update_interval: 1d
